trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '18.x'
    checkLatest: true
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'install --legacy-peer-deps'
  displayName: 'Install dependencies'

- task: SonarCloudPrepare@3
  inputs:
    SonarQube: 'SonarCloud-Connection'
    organization: 'devsecops-genese'
    scannerMode: 'cli'
    cliScannerVersion: '7.2.0.5079'
    configMode: 'manual'
    cliProjectKey: 'DevSecOps-Genese_genese_demo'
    cliProjectName: 'genese_demo'
    cliSources: '.'
  displayName: 'Prepare SonarCloud Connections'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'
  displayName: 'Build application'

- task: SonarCloudAnalyze@3
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'
  displayName: 'Run Sonarloud Analysis'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'dist'
    includeRootFolder: false   # keeps "dist" folder inside zip, or false if you want only files
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
    verbose: true
  displayName: 'Archieve Build Artifacts'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish artifacts'
